//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinoApp.Areas.Kino.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieDescription
    {
        public int MovieId { get; set; }
        public string Desciption { get; set; }
        public Nullable<double> Time { get; set; }
        public Nullable<int> Scale { get; set; }
    }
}
