//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinoApp.Areas.Kino.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersMovie
    {
        public int UserId { get; set; }
        public short MovieId { get; set; }
        public string MovieName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> IsWatched { get; set; }
    }
}
